site_name: Task
repo_url: https://github.com/DeronW/task/

nav:
  - 介绍[done]: intro.zh.md
  - 安装[done]: installation.zh.md
  - 使用: usage.zh.md
  - API: api_reference.zh.md
  - 风格指南: styleguide.zh.md
  - Changelog: changelog.md
  - 社区: community.zh.md
  - 贡献[done]: contributing.zh.md
  - 发布[done]: releasing.zh.md
  - 版本[done]: taskfile_versions.zh.md
  - 捐助[done]: donate.zh.md

theme:
  name: readthedocs
  locale: zh
  highlightjs: true

