site_name: Task
repo_url: https://github.com/DeronW/task/

nav:
  - 介绍: intro.zh.md
  - 安装: installation.zh.md
  - 用法: usage.zh.md
  - API参考: api_reference.zh.md
  - 风格指南: styleguide.zh.md
  - Changelog: changelog.md
  - 社区: community.zh.md
  - 贡献: contributing.zh.md
  - 发布: releasing.zh.md
  - 版本: taskfile_versions.zh.md
  - 捐助: donate.zh.md

theme:
  name: readthedocs
  locale: zh
  highlightjs: true

